=== api-evangelist/hypixel/json-schema/hypixel-public-api-sky-block-profile-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/hypixel/refs/heads/main/json-schema/hypixel-public-api-sky-block-profile-schema.json",
  "title": "SkyBlockProfile",
  "description": "SkyBlockProfile schema from Hypixel Public API",
  "type": "object",
  "properties": {
    "profile_id": {
      "type": "string",
      "format": "uuid",
      "example": "ad8fefaa8351454bb739a4eaa872173f"
    },
    "members": {
      "description": "A map of member UUIDs to member profiles objects",
      "type": "object",
      "properties": {
        "player_id": {
          "type": "string",
          "format": "uuid",
          "example": "ad8fefaa8351454bb739a4eaa872173f"
        },
        "profile": {
          "type": "object",
          "properties": {
            "deletion_notice": {
              "description": "If this field exists, the member profile is marked as deleted",
              "nullable": true,
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "integer",
                  "format": "int64",
                  "example": 1748544600000
                }
              }
            }
          }
        }
      }
    },
    "cute_name": {
      "description": "The cute name of the profile, only provided on the profiles endpoint",
      "nullable": true,
      "type": "string",
      "example": "ExamplePlayer"
    },
    "selected": {
      "description": "Whether or not this is the currently selected profile, only provided on the profiles endpoint",
      "nullable": true,
      "type": "boolean",
      "example": true
    },
    "community_upgrades": {
      "nullable": true,
      "type": "object"
    },
    "banking": {
      "description": "Information about the bank account for this profile, only present if the API banking setting is enabled",
      "nullable": true,
      "type": "object",
      "properties": {
        "balance": {
          "type": "number",
          "format": "double",
          "example": 1.0
        },
        "transactions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "timestamp": {
                "type": "integer",
                "format": "int64",
                "example": 1748544600000
              },
              "action": {
                "type": "string",
                "enum": [
                  "DEPOSIT",
                  "WITHDRAW"
                ],
                "example": "DEPOSIT"
              },
              "initiator_name": {
                "type": "string",
                "example": "ExamplePlayer"
              },
              "amount": {
                "type": "number",
                "format": "double",
                "example": 1.0
              }
            }
          }
        }
      }
    },
    "game_mode": {
      "description": "The SkyBlock game mode of the profile, not present if normal mode",
      "nullable": true,
      "type": "string",
      "enum": [
        "ironman",
        "island",
        "bingo"
      ],
      "example": "ironman"
    }
  }
}

=== api-evangelist/hypixel/examples/hypixel-public-api-sky-block-profile-example.json
{
  "profile_id": "ad8fefaa8351454bb739a4eaa872173f",
  "members": {
    "player_id": "ad8fefaa8351454bb739a4eaa872173f",
    "profile": {
      "deletion_notice": {
        "timestamp": 1748544600000
      }
    }
  },
  "cute_name": "ExamplePlayer",
  "selected": true,
  "community_upgrades": {},
  "banking": {
    "balance": 1.0,
    "transactions": [
      {
        "timestamp": 1748544600000,
        "action": "DEPOSIT",
        "initiator_name": "ExamplePlayer",
        "amount": 1.0
      }
    ]
  },
  "game_mode": "ironman"
}
