=== api-evangelist/hypixel/json-schema/hypixel-public-api-sky-block-auction-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/hypixel/refs/heads/main/json-schema/hypixel-public-api-sky-block-auction-schema.json",
  "title": "SkyBlockAuction",
  "description": "SkyBlockAuction schema from Hypixel Public API",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string",
      "format": "objectid",
      "example": "5fcbf9d9d295e80a766f3b14"
    },
    "uuid": {
      "type": "string",
      "format": "uuid",
      "example": "ad8fefaa8351454bb739a4eaa872173f"
    },
    "auctioneer": {
      "type": "string",
      "format": "uuid",
      "example": "ad8fefaa8351454bb739a4eaa872173f"
    },
    "profile_id": {
      "type": "string",
      "format": "uuid",
      "example": "ad8fefaa8351454bb739a4eaa872173f"
    },
    "coop": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid"
      }
    },
    "start": {
      "type": "number",
      "format": "int64",
      "example": 1.0
    },
    "end": {
      "type": "number",
      "format": "int64",
      "example": 1.0
    },
    "item_name": {
      "type": "string",
      "example": "ExamplePlayer"
    },
    "item_lore": {
      "type": "string",
      "example": "example"
    },
    "extra": {
      "type": "string",
      "example": "example"
    },
    "category": {
      "type": "string",
      "example": "example"
    },
    "tier": {
      "type": "string",
      "example": "example"
    },
    "starting_bid": {
      "type": "number",
      "example": 1.0
    },
    "item_bytes": {
      "type": "object",
      "properties": {
        "type": {
          "type": "number",
          "example": 1.0
        },
        "data": {
          "type": "string",
          "example": "example"
        }
      }
    },
    "claimed": {
      "type": "boolean",
      "example": true
    },
    "claimed_bidders": {
      "type": "array"
    },
    "highest_bid_amount": {
      "type": "number",
      "example": 1.0
    },
    "bids": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "auction_id": {
            "type": "string",
            "format": "uuid",
            "example": "ad8fefaa8351454bb739a4eaa872173f"
          },
          "bidder": {
            "type": "string",
            "format": "uuid",
            "example": "ad8fefaa8351454bb739a4eaa872173f"
          },
          "profile_id": {
            "type": "string",
            "format": "uuid",
            "example": "ad8fefaa8351454bb739a4eaa872173f"
          },
          "amount": {
            "type": "number",
            "example": 1.0
          },
          "timestamp": {
            "type": "number",
            "format": "int64",
            "example": 1.0
          }
        }
      }
    }
  },
  "example": {
    "uuid": "409a1e0f261a49849493278d6cd9305a",
    "auctioneer": "347ef6c1daac45ed9d1fa02818cf0fb6",
    "profile_id": "347ef6c1daac45ed9d1fa02818cf0fb6",
    "coop": [
      "347ef6c1daac45ed9d1fa02818cf0fb6"
    ],
    "start": 1573760802637,
    "end": 1573761102637,
    "item_name": "Azure Bluet",
    "item_lore": "\u00a7f\u00a7lCOMMON",
    "extra": "Azure Bluet Red Rose",
    "category": "blocks",
    "tier": "COMMON",
    "starting_bid": 1,
    "item_bytes": {
      "type": 0,
      "data": "H4sIAAAAAAAAAB2NQQqCQBhGv1ErHaKu0KoLtGtnarRIhTpA/OGfDIwZ4wxUF/IeHiyyto/3eBKIIJQEIDx4qsJaYJK07m6FhG+p9hEdVMV7TXU3Wh+JWaW6h6ZXhODYGg5/LeZDfxt6nZR5XhYhgoIaxmKE8dsZXu20YwuJZfa0hmJrjbo6y134f8pTll5O5TnbbgAP05Qaqhk+8AVIrd2eoAAAAA=="
    },
    "claimed": true,
    "claimed_bidders": [],
    "highest_bid_amount": 7607533,
    "bids": [
      {
        "auction_id": "409a1e0f261a49849493278d6cd9305a",
        "bidder": "99748e629dee463892f68abf3a780094",
        "profile_id": "99748e629dee463892f68abf3a780094",
        "amount": 7607533,
        "timestamp": 1573760824844
      }
    ]
  }
}

=== api-evangelist/hypixel/examples/hypixel-public-api-sky-block-auction-example.json
{
  "_id": "5fcbf9d9d295e80a766f3b14",
  "uuid": "ad8fefaa8351454bb739a4eaa872173f",
  "auctioneer": "ad8fefaa8351454bb739a4eaa872173f",
  "profile_id": "ad8fefaa8351454bb739a4eaa872173f",
  "coop": [
    "ad8fefaa-8351-454b-b739-a4eaa872173f"
  ],
  "start": 1.0,
  "end": 1.0,
  "item_name": "ExamplePlayer",
  "item_lore": "example",
  "extra": "example",
  "category": "example",
  "tier": "example",
  "starting_bid": 1.0,
  "item_bytes": {
    "type": 1.0,
    "data": "example"
  },
  "claimed": true,
  "claimed_bidders": [
    "500123"
  ],
  "highest_bid_amount": 1.0,
  "bids": [
    {
      "auction_id": "ad8fefaa8351454bb739a4eaa872173f",
      "bidder": "ad8fefaa8351454bb739a4eaa872173f",
      "profile_id": "ad8fefaa8351454bb739a4eaa872173f",
      "amount": 1.0,
      "timestamp": 1.0
    }
  ]
}
